import Head from "next/head";
// import Counter from "../components/Counter";
// import Slider from "../components/Slider";

const Home = () => {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="home">
        <section></section>
      </main>
    </>
  );
};

export default Home;
